[project]
name = "maersk-kiro-demo"
version = "0.1.0"
description = "Audio Transcription to Kiro Spec Application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0",
    "boto3>=1.34.0",
    "pytest>=8.4.1",
]
